metadata:
  generation_kwargs:
    reasoning: false
    temperature: 3e-2
  tgc_search_kwargs:
    max_tg_channels: 2
    max_post_per_channel: 2
  web_retrieve_kwargs:
    max_search_results: 5
    n_chunks: 3
    chunk_size: 1000
    chunk_overlap: 300
  web:
    user_agents:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/129.0.0.0 Safari/537.36
    - Mozilla/5.0 (Windows NT 11.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/128.0.0.0 Safari/537.36
    - Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/127.0.0.0 Safari/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 15_0) AppleWebKit/537.36 (KHTML, like
      Gecko) Chrome/129.0.0.0 Safari/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/537.36 (KHTML, like
      Gecko) Chrome/128.0.0.0 Safari/537.36
    - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0
      Safari/537.36
    - Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/128.0.0.0 Safari/537.36
    - Mozilla/5.0 (Linux; Android 15; SM-S928B) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/129.0.0.0 Mobile Safari/537.36
    - Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/128.0.0.0 Mobile Safari/537.36
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
    - Mozilla/5.0 (Windows NT 10.0; WOW64; rv:129.0) Gecko/20100101 Firefox/129.0
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 15.0; rv:130.0) Gecko/20100101 Firefox/130.0
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 14.5; rv:129.0) Gecko/20100101 Firefox/129.0
    - Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0
    - Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0
    - Mozilla/5.0 (Android 15; Mobile; rv:130.0) Gecko/130.0 Firefox/130.0
    - Mozilla/5.0 (Android 14; Mobile; rv:129.0) Gecko/129.0 Firefox/129.0
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 15_0) AppleWebKit/605.1.15 (KHTML, like
      Gecko) Version/18.0 Safari/605.1.15
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like
      Gecko) Version/17.5 Safari/605.1.15
    - Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15
      (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1
    - Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15
      (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1
    - Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like
      Gecko) Version/18.0 Mobile/15E148 Safari/604.1
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 15_0) AppleWebKit/537.36 (KHTML, like
      Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/126.0.0.0 Safari/537.36
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0
    - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0
      Safari/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15 (KHTML, like
      Gecko) Version/17.4 Safari/605.1.15
    - Mozilla/5.0 (Linux; Android 14; SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/126.0.0.0 Mobile Safari/537.36
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/130.0.0.0 Safari/537.36
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 15_1) AppleWebKit/605.1.15 (KHTML, like
      Gecko) Version/18.1 Safari/605.1.15
    - Mozilla/5.0 (Linux; Android 15; Pixel 9) AppleWebKit/537.36 (KHTML, like Gecko)
      Chrome/130.0.0.0 Mobile Safari/537.36
    tgstat_endpoints:
    - games
    - health
    - transport
    - courses
    - music
    - pics
    - nature
    - religion
    - tech
    - psychology
    - shock
    - video
    - apps
    - construction
    - adult
    - other
    - telegram
    - news
    - gambling
    - language
    - marketing
    - economics
    - instagram
    - design
    - food
    - handmade
    - entertainment
    - babies
    - erotica
    - travels
    - art
    - education
    - blogs
    - books
    - medicine
    - crypto
    - politics
    - sales
    - law
    - esoterics
    - business
    - sport
    - quotes
    - career
    - beauty
    - edutainment
    - darknet
