[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tgc_bot"
version = "0.1.0"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-dir]
src = "src"